### ISSUE TITLE
argument help is misleading

### ISSUE THREAD

**Issue by timfinholm** [Veil-Framework/Veil-Ordnance#6]
around line 44 --
shell_in.add_argument(
        '--list-encoders', default=False, action='store_true',
        help="Lists all available payloads.")

preferable --
shell_in.add_argument(
        '--list-encoders', default=False, action='store_true',
        help="Lists all available encoders.")

**Comment by ChrisTruncer** [comment]
Fixed.  Good catch on that.  Thanks for letting me know!
